config/routes.rb
Rails.application.routes.draw do

  get '/' => 'home#index'

  resources :stories do
    member do
      get :edit_body
    end
    resources :characters
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :story
end

app/models/story.rb
class Story < ApplicationRecord

  has_many :characters

  def published?
    published_at.present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  before_action :get_story

  def new
    @character = @story.characters.new
  end

  def create
    @character = @story.characters.new(allowed_params)
    if @character.save
      flash[:notice] = "Created character!"
      if params[:commit] == 'I have another character'
        redirect_to new_story_character_path
      else
        redirect_to story_edit_body_path(@story)
      end
    else
      flash[:alert] = "Error creating character"
      render :new
    end
  end

protected

  def get_story
    @story = Story.find(params[:story_id])
  end

  def allowed_params
    params.require(:character).permit(
      :name, :gender, :hobbies, :clothes, :traits,
      :fun_facts, :eye_color, :hair, :location, :special_abilities)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all.limit(10).offset(0)
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(allowed_params)
    if @story.save
      flash[:notice] = "Story created!"
      redirect_to new_story_character_path(@story)
    else
      flash[:error] = "Failure to save story :("
      render :new
    end
  end

  def edit
    @story = Story.find(params[:id])
  end

  def edit_body
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])
  end

protected

  def allowed_params
    params.require(:story).permit(:author, :title, :plot)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/characters/new.html.erb
<h2>Add Character</h2>

<%= form_for [@story, @character] do |form| %>

<ul class="character">
  <li> Name <input type="text" name="character[name]" value="Example text"/>
  <li>
    <input type="radio" name="gender" value="character[girl]" checked> Girl
    <input type="radio" name="gender" value="character[boy]"> Boy
    <input type="radio" name="gender" value="character[other]"> Other
  <li> Hobbies <input type="text" name="character[hobbies]" value="Soccer, badminton"/>
  <li> Clothes <input type="text" name="character[clothes]" value="Red shirt, blue pants, pink underwear"/>
  <li> Traits <input type="text" name="character[traits]" value="Kind,brave, smart"/>
  <li> Fun facts <input type="text" name="character[fun_facts]" value="Her dad faught in the war and she lives with her mom, brother and maid"/>
  <li> Eye color <input type="text" name="character[eye_color]" value="Hazel"/>
  <li> Hair <input type="text" name="character[hair]" value="Curly and red with frizz on the top"/>
  <li> Location <input type="text" name="character[location]" value="New York"/>
  <li> Special abilities (Optional) <input type="text" name="character[special_abilities]" value="She can fly"/>
</ul>

<p>
  <!-- <a class="button" href="">I have another character</a> -->
  <%= form.submit value: "I have another character" %>

<p>
  <!-- <a class="button" href="story.html">Next</a> -->
  <%= form.submit value: "All done" %>

<% end -%>

app/views/home/index.html.erb
<p>
  <a class="button" href="/stories/new">New story</a>
<p>
  <a class="button" href="/stories">Load story</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Once Upon A DIY</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><a href="/">Once Upon A DIY</a></h1>

    <%= yield %>

  </body>
</html>

app/views/stories/edit_body.html.erb
<%= form_for @story do |form| %>
  <textarea class="body" name="story[body]">
  Here is your story.... start writing!

  </textarea>

  <p>
    <%= form.submit value: 'Next' %>

<% end -%>

app/views/stories/index.html.erb
<% if @stories.blank? %>
  <p>No stories yet!
  <p>Why don't you <%= link_to 'write one?', new_story_path %>
<% end %>

<ul>
<% @stories.each do |story| -%>
  <li>
    <%= link_to story.title || "Untitled", story_path(story) %>
    by <%= story.author || "Anonymous" %>
  </li>
<% end -%>
</ul>

app/views/stories/new.html.erb
<%= form_for @story do %>
<p>
  <label for="title">Author:</label>
  <input type="text" name="story[author]" class="author" value="What's your name?"/>
<p>
  <label for="title">Title:</label>
  <input type="text" name="story[title]" class="title" value="What's your story called?"/>
<p>
  <label for="plot">Plot:</label>
  <textarea name="story[plot]" class="plot">Summarize what your story is about</textarea>

<p>
  <input type="submit" value="Save" style="font-size: 1em;" />

<% end %>

app/views/stories/show.html.erb
Hello this is a story!

<p>Author: <%= @story.author %>

<p>Title: <%= @story.title %>

<p>Plot: <%= @story.plot %>

<p>Characters: coming soon

<p>Body: <%= @story.body %>

<p>Published: <%= @story.published_at %>

<p>Illustrations: coming soon